from __future__ import annotations

from seller_core.models import BodyEncoding, EndpointSpec


ETSY_V3_BASE_URL = "https://api.etsy.com/v3/application"


CORE_TOOL_SPECS: tuple[EndpointSpec, ...] = (
    EndpointSpec(
        tool_name="create_draft_listing",
        operation_id="createDraftListing",
        method="POST",
        path_template="/shops/{shop_id}/listings",
        description="Create a draft listing for a shop.",
        scopes=("listings_w",),
        path_params=("shop_id",),
        query_params=("legacy",),
        body_encoding=BodyEncoding.FORM,
        required_body_fields=(
            "quantity",
            "title",
            "description",
            "price",
            "who_made",
            "when_made",
            "taxonomy_id",
        ),
        notes=(
            "Etsy's listings tutorial documents quantity, title, description, price, who_made, when_made, and taxonomy_id as minimum listing fields.",
            "Physical listings also require shipping_profile_id and readiness_state_id; active listings require image_ids.",
        ),
    ),
    EndpointSpec(
        tool_name="update_listing",
        operation_id="updateListing",
        method="PATCH",
        path_template="/shops/{shop_id}/listings/{listing_id}",
        description="Update listing fields such as state, price, title, or type.",
        scopes=("listings_w",),
        path_params=("shop_id", "listing_id"),
        body_encoding=BodyEncoding.FORM,
        notes=(
            "Etsy examples use PATCH for updateListing.",
        ),
    ),
    EndpointSpec(
        tool_name="delete_listing",
        operation_id="deleteListing",
        method="DELETE",
        path_template="/shops/{shop_id}/listings/{listing_id}",
        description="Delete a listing from a shop.",
        scopes=("listings_d",),
        path_params=("shop_id", "listing_id"),
        notes=(
            "Etsy's listings tutorial documents deleteListing as part of the listing lifecycle and requires listings_d scope.",
        ),
    ),
    EndpointSpec(
        tool_name="get_listing",
        operation_id="getListing",
        method="GET",
        path_template="/listings/{listing_id}",
        description="Get a single listing by listing id.",
        path_params=("listing_id",),
        query_params=("includes", "language"),
        scopes=("listings_r",),
    ),
    EndpointSpec(
        tool_name="get_shop_listings",
        operation_id="getListingsByShop",
        method="GET",
        path_template="/shops/{shop_id}/listings",
        description="List a shop's listings with pagination and filters.",
        path_params=("shop_id",),
        query_params=(
            "state",
            "limit",
            "offset",
            "sort_on",
            "sort_order",
            "includes",
            "language",
        ),
        scopes=("listings_r",),
    ),
    EndpointSpec(
        tool_name="search_marketplace",
        operation_id="findAllListingsActive",
        method="GET",
        path_template="/listings/active",
        description="Search active marketplace listings.",
        query_params=(
            "keywords",
            "sort_on",
            "sort_order",
            "min_price",
            "max_price",
            "color",
            "color_accuracy",
            "shop_location",
            "category",
            "taxonomy_id",
            "limit",
            "offset",
        ),
        scopes=(),
    ),
    EndpointSpec(
        tool_name="get_listing_inventory",
        operation_id="getListingInventory",
        method="GET",
        path_template="/listings/{listing_id}/inventory",
        description="Read a listing's inventory products and offerings.",
        path_params=("listing_id",),
        scopes=("listings_r",),
        notes=(
            "Etsy's listings tutorial references getListingInventory as the source of truth before updateListingInventory calls.",
        ),
    ),
    EndpointSpec(
        tool_name="update_listing_inventory",
        operation_id="updateListingInventory",
        method="PUT",
        path_template="/listings/{listing_id}/inventory",
        description="Replace the full inventory document for a listing.",
        path_params=("listing_id",),
        body_encoding=BodyEncoding.JSON,
        required_body_fields=("products",),
        scopes=("listings_w",),
        notes=(
            "Etsy's listings tutorial documents this as a full replacement update: send the complete products array, not a partial patch.",
        ),
    ),
    EndpointSpec(
        tool_name="get_shop_info",
        operation_id="getShop",
        method="GET",
        path_template="/shops/{shop_id}",
        description="Get shop metadata and summary fields.",
        path_params=("shop_id",),
        query_params=("includes",),
        scopes=("shops_r",),
    ),
    EndpointSpec(
        tool_name="update_shop",
        operation_id="updateShop",
        method="PUT",
        path_template="/shops/{shop_id}",
        description="Update shop title, announcement, and sale messages.",
        path_params=("shop_id",),
        body_encoding=BodyEncoding.FORM,
        scopes=("shops_r", "shops_w"),
    ),
    EndpointSpec(
        tool_name="get_orders",
        operation_id="getShopReceipts",
        method="GET",
        path_template="/shops/{shop_id}/receipts",
        description="List a shop's orders/receipts.",
        path_params=("shop_id",),
        query_params=(
            "limit",
            "offset",
            "was_paid",
            "was_shipped",
            "was_delivered",
            "min_created",
            "max_created",
            "min_last_modified",
            "max_last_modified",
            "sort_on",
            "sort_order",
        ),
        scopes=("transactions_r",),
    ),
    EndpointSpec(
        tool_name="get_order_details",
        operation_id="getShopReceipt",
        method="GET",
        path_template="/shops/{shop_id}/receipts/{receipt_id}",
        description="Get a single order/receipt.",
        path_params=("shop_id", "receipt_id"),
        query_params=("includes",),
        scopes=("transactions_r",),
    ),
    EndpointSpec(
        tool_name="get_payments",
        operation_id="getPayments",
        method="GET",
        path_template="/shops/{shop_id}/payments",
        description="List posted payments for a shop.",
        path_params=("shop_id",),
        scopes=("transactions_r",),
        notes=(
            "Etsy's payments tutorial positions payments as read-only financial reporting data, typically available after fulfillment.",
        ),
    ),
    EndpointSpec(
        tool_name="get_reviews",
        operation_id="getReviewsByShop",
        method="GET",
        path_template="/shops/{shop_id}/reviews",
        description="List reviews for a shop.",
        path_params=("shop_id",),
        query_params=("listing_id", "limit", "offset"),
        scopes=("transactions_r",),
        notes=(
            "The exact shop reviews resource path is inferred from Etsy's operation naming and tutorial references because the reference SPA does not expose a static path in crawlable HTML.",
        ),
    ),
    EndpointSpec(
        tool_name="get_taxonomy_nodes",
        operation_id="getSellerTaxonomyNodes",
        method="GET",
        path_template="/seller-taxonomy/nodes",
        description="Get seller taxonomy nodes for listing categorization.",
        query_params=("taxonomy_id",),
        scopes=(),
        notes=(
            "The seller taxonomy resource path is inferred from Etsy's operation naming and tutorial references because the reference SPA does not expose a static path in crawlable HTML.",
        ),
    ),
)


CORE_TOOL_INDEX = {spec.tool_name: spec for spec in CORE_TOOL_SPECS}
